### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by jcohenadad**
to match https://zenodo.org/record/4299148#.YYxHyr3MKPQ

### CODE REVIEW

**Comment by kousu** [comment]
Hmm so LICENSE file *in* https://zenodo.org/record/4299148#.YYxHyr3MKPQ is still MIT

2021-11-13-113620_134x81_scrot

2021-11-13-113607_850x294_scrot

2021-11-13-113612_890x452_scrot

which means it's contradicting itself on Zenodo. Are you planning to release the updated copy from Github to Zenodo?

**Comment by jcohenadad** [comment]
oh, i see. Good catch @kousu .

I think the procedure is for me to create a new version:
image

but this version being based on a GH release, I think the steps are:
- release on GH (with new license file)
- create new version on zenodo

**Comment by kousu** [comment]
> oh, i see. Good catch @kousu .
> 
> I think the procedure is for me to create a new version: image
> 
> but this version being based on a GH release, I think the steps are:
> 
>     * release on GH (with new license file)
> 
>     * create new version on zenodo

Cool, that sounds good.

To be clean about it, is it possible to change the license on the existing version to MIT? Or does Zenodo only record one license for *all* versions? Or does it not let you change the license once published, because that would break the citability? If it's the latter two cases..well...I guess the best we can do is upload a repaired, matching version, and hope no one ever digs into the older versions and realizes their license is legally ambiguous.

**Comment by jcohenadad** [comment]
> To be clean about it, is it possible to change the license on the existing version to MIT? Or does Zenodo only record one license for all versions? Or does it not let you change the license once published, because that would break the citability? If it's the latter two cases..well...I guess the best we can do is upload a repaired, matching version, and hope no one ever digs into the older versions and realizes their license is legally ambiguous.

i think it's fine to just repair. if you could approve we can merge and i'll take care of the release

**Review by kousu — APPROVED** [review]

**Comment by jcohenadad** [comment]
oopsi, we'll have to wait a bit:
image

**Comment by jcohenadad** [comment]
I tried creating a new version but i'm getting this:

image

even though the license file changed 🤷‍♂️

**Pull request merged**
